version: "3.7"

services:
  svoyak_application:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-application
    volumes:
      - "../data/uploads:/application/data/uploads"
      - "../data/logs:/tmp/logs"
      - "../../configs:/application/configs"
    depends_on:
      - svoyak_postgres
      - svoyak_session
    ports:
      - 2345:2345 # Remote debug

  svoyak_session:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-session
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - svoyak_postgres
    ports:
      - 2346:2345 # Remote debug

  svoyak_chat:
    restart: always
    build:
      context: ../
      dockerfile: deployments/Dockerfile-chat
    volumes:
      - "../../configs:/application/configs"
    depends_on:
      - svoyak_postgres

  svoyak_postgres:
    image: postgres:12.0
    restart: always
    environment:
      POSTGRES_USER: svoyak
      POSTGRES_PASSWORD: top_secret_goes_here
    volumes:
      - "../db/migrations/:/docker-entrypoint-initdb.d"
      - "pg_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432

  svoyak_swagger:
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "../api:/app"

  svoyak_nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - svoyak_chat
      - svoyak_application
    volumes:
      - "../configs/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../data/:/data"
    ports:
      - 3000:3000

volumes:
  pg_data:
